### ISSUE TITLE
Как создать мигрции ?

### ISSUE THREAD

**Issue by VladBeglik** [ilyabreev/ClickHouse.Net.Migrations#2]
Здавствуйте, вы могли бы рассписать немного подробнее как создать миграции в базу данных ?

**Comment by ilyabreev** [comment]
Добрый день!

Чтобы создать миграцию, нужно создать новый класс, как в примере:

[test/ClickHouse.Net.Migrations.Tests/DefautClickHouseMigrationLocatorTests/Migrations/_20180716143700_EmptyMigration.cs](https://github.com/ilyabreev/ClickHouse.Net.Migrations/blob/4f2cb137d0a3fb9263221367cde180a0d2f69604/test/ClickHouse.Net.Migrations.Tests/DefautClickHouseMigrationLocatorTests/Migrations/_20180716143700_EmptyMigration.cs)

А затем внутри метода `Process` написать всю логику, которая вам необходима для применения вашей миграции.
